### 全プレイヤー取得
GET http://localhost:8080/api/v1/players

###プレイヤー作成
POST http://localhost:8080/api/v1/players
Content-Type: application/json

{
  "name": "ともや"
}

### 単一プレイヤー取得
GET http://localhost:8080/api/v1/players/99ef7fdb-fc15-46e6-a0fb-a8760ce5e82f

### プレイヤー削除
DELETE  http://localhost:8080/api/v1/players/3821cd5a-de7c-4706-a1c2-79c152e427f5



### 全リーグ取得
GET http://localhost:8080/api/v1/leagues

###リーグ作成
POST http://localhost:8080/api/v1/leagues
Content-Type: application/json

{
  "name": "小次郎麻雀大会"
}

### 一つのリーグ取得
GET http://localhost:8080/api/v1/leagues/d15f4a35-96c9-43e6-a0b4-b95454472132

###リーグ削除
DELETE http://localhost:8080/api/v1/leagues/d15f4a35-96c9-43e6-a0b4-b95454472132



### 試合作成
POST http://localhost:8080/api/v1/leagues/359eec6f-03a6-46b3-bc5c-cd9ca2c87e0a/matches
Content-Type: application/json

{
  "matchNumber": 1,
  "ruleType": "INITIAL"
}

###

### リーグ内の試合一覧取得
GET http://localhost:8080/api/v1/leagues/359eec6f-03a6-46b3-bc5c-cd9ca2c87e0a/matches

###

### 試合更新
PUT http://localhost:8080/api/v1/leagues/359eec6f-03a6-46b3-bc5c-cd9ca2c87e0a/matches/884caec9-3e50-48ed-999b-2c63786ae7a3
Content-Type: application/json

{
  "matchNumber": 2,
  "ruleType": "UPPER"
}

###

### 試合削除
DELETE http://localhost:8080/api/v1/leagues/359eec6f-03a6-46b3-bc5c-cd9ca2c87e0a/matches/884caec9-3e50-48ed-999b-2c63786ae7a3


